### ISSUE TITLE
cannot load such file -- bigdecimal/util (LoadError)

### ISSUE THREAD

**Issue by renrenfree** [aliyun/aliyun-odps-fluentd-plugin#2]
cannot load such file -- bigdecimal/util (LoadError)

**Comment by dongxiao1198** [comment]
Where did you get this error？

**Comment by renrenfree** [comment]
/usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- bigdecimal/util (LoadError)
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/fluent/.gem/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/big_decimal/conversions.rb:2:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/fluent/.gem/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/core_ext/object/json.rb:4:in`<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/fluent/.gem/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/json/encoding.rb:1:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /home/fluent/.gem/ruby/2.2.0/gems/activesupport-4.2.5/lib/active_support/json.rb:2:in`<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /home/fluent/.gem/ruby/2.2.0/gems/protobuf-3.5.5/lib/protobuf.rb:9:in `<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in`require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in`require'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/serialize/serializer.rb:20:in `<top (required)>'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/stream_writer.rb:25:in`require_relative'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/stream_writer.rb:25:in `<top (required)>'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/stream_client.rb:21:in`require_relative'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/stream_client.rb:21:in `<top (required)>'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/out_aliyun_odps.rb:27:in`require_relative'
    from /home/fluent/.gem/ruby/2.2.0/gems/fluent-plugin-aliyun-odps-0.1.0/lib/fluent/plugin/out_aliyun_odps.rb:27:in `initialize'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/plugin.rb:128:in`new'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/plugin.rb:128:in `new_impl'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/plugin.rb:57:in`new_output'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:127:in `add_match'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:60:in`block in configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:54:in `each'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/agent.rb:54:in`configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/root_agent.rb:82:in `configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:117:in`configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/engine.rb:91:in `run_configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:515:in`run_configure'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:146:in `block in start'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:352:in`call'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:352:in `main_process'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:325:in`block in supervise'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:324:in `fork'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:324:in`supervise'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/supervisor.rb:142:in `start'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/lib/fluent/command/fluentd.rb:171:in`<top (required)>'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in`require'
    from /usr/lib/ruby/gems/2.2.0/gems/fluentd-0.12.19/bin/fluentd:6:in `<top (required)>'
    from /usr/bin/fluentd:23:in`load'
    from /usr/bin/fluentd:23:in `<main>'

**Comment by huichen** [comment]
@renrenfree  需要安装依赖

gem install bigdecimal
