### ISSUE TITLE
怎样使用json格式的日志

### ISSUE THREAD

**Issue by renrenfree** [aliyun/aliyun-odps-fluentd-plugin#3]
特别原因 限制了source格式 请问match 如何使用json？

**Comment by dongxiao1198** [comment]
是source数据是json？如果是的话在source里面format json就行。
match不需要关心是否为json

**Comment by renrenfree** [comment]
fields(Required): must match the keys in source.

**Comment by dongxiao1198** [comment]
这个是指的field中指定的key必须在source中存在，如果整个source是个json,需要是个json map才行。
